### ISSUE TITLE
Pad before convolution to avoid artifacts

### ISSUE THREAD

**Issue by rafaelvalle** [distillpub/post--deconv-checkerboard#5]
First of all, thank you all for the awesome post.
In the text describing the code you suggest padding before applying convolution to avoid boundary artifacts. When one applies, for example, a Laplacian with (1,1) zero padded image, it will likely produce an edge, i.e. artifact, between the limits of the image and the zero-padding.
For this reason, I'm not clear how padding before applying convolution would avoid boundary artifacts!

**Comment by colah** [comment]
Hello!

The trick is that, instead of zero-padding your image, you use symmetric padding (which copies entries from the boundary of the image). 

I recommend using `tf.pad(..., mode='SYMMETRIC')` followed by `tf.conv2d(..., padding='VALID')` to avoid boundary effects.

**Comment by rafaelvalle** [comment]
Got it! By padding you don't mean zero-padding but copying the edges of the image!
For future visitors, it would be very helpful if you could add this information to the post itself!

**Comment by PK15946** [comment]
@colah Hello, I am not understand why using mode='SYMMETRIC' helps to get rid of boundary artifacts, it would be great help if you can provide some insights of it.
