### ISSUE TITLE
 Bilinear-resize Convolution Figure has some error

### ISSUE THREAD

**Issue by redpanda3** [distillpub/post--deconv-checkerboard#7]
Dear Author,

![image](https://cloud.githubusercontent.com/assets/28216801/25562638/0ccfb530-2dbe-11e7-86c6-848facd16a02.png)
From my perspective, in this figure, in the second row, first column, 1/2*a have to be added, to make sure that sum of each row should be a+b+c. 

If you have any question, welcome to discuss with me.

Best,
redpanda3

**Comment by redpanda3** [comment]
@colah Hello? Am I right?

**Comment by colah** [comment]
Yep! Thanks for catching that. I'll put this on my todo list to fix.

**Comment by colah** [comment]
Fixed!

![image](https://cloud.githubusercontent.com/assets/61658/26371988/4c315dd2-3fb1-11e7-979c-d9b4c0a3b524.png)

**Comment by redpanda3** [comment]
Aha.
