### ISSUE TITLE
Are you using one-time resize or multiple time resize?

### ISSUE THREAD

**Issue by raingo** [distillpub/post--deconv-checkerboard#8]
For example, if I want to upscale from 8x8 to 128x128, which one is the right way?

1. resize => conv => conv => conv => conv
2. resize,conv => resize,conv => resize,conv => resize,conv

**Comment by raingo** [comment]
@colah PTAL

**Comment by colah** [comment]
We did multiple resize and convs, but I don't think any detailed examination of the benefits of each has been done.

One reason to do multiple resizes and convs is that it allows you to do more work where you can integrate global context.

**Comment by colah** [comment]
Please see also our other paper exploring large image models: https://arxiv.org/pdf/1610.09585.pdf
